stages:
  # load-data:
  #   cmd: python main.py load-data run
  #     --date 230101
  #     --store-id 399
  #   deps:
  #     - src/load_data.py

  transform:
    cmd: python main.py preprocess transform
      --input-file transactions.csv
      --output-file transaction_fpg.csv
      --item-id SDeptName
    deps:
      - src/preprocess.py
      - data/raw/transactions.csv
    outs:
      - data/interim/transaction_fpg.csv

  fpgrowth:
    cmd: python main.py fpgrowth run
      --input-file transaction_fpg.csv
    deps:
      - src/fpg_analyzer.py

  huim:
    cmd: python main.py huim run
      --input-file transaction_fpg.csv
    deps:
      - src/huim_analyzer.py
