stages:
  # load-data:
  #   cmd: python main.py load-data run
  #     --date 230101
  #     --store-id 399
  #   deps:
  #     - src/load_data.py

  # transform:
  #   cmd: python main.py preprocess transform
  #     --input-file transactions.csv
  #     --output-file transaction_fpg.csv
  #     --item-id SDeptName
  #   deps:
  #     - src/preprocess.py
  #     - data/raw/transactions.csv

  # fpgrowth:
  #   cmd: python main.py association_rules run_fpgrowth
  #     --input-file transaction_fpg.csv
  #   deps:
  #     - src/association_rules.py

  # huim:
  #   cmd: python main.py association_rules run_huim
  #     --input-file transaction_fpg.csv
  #   deps:
  #     - src/association_rules.py

  extract_layout:
    cmd: python main.py preprocess extract-layout
      --pptx layout.pptx
      --out  layout.csv
    deps:
      - src/preprocess.py
      - data/external/layout.pptx

  layout-opt-pipeline:
    cmd: python main.py layout-opt run
      --assoc-rules-path association_rules.csv
      --freq-itemsets-path frequent_itemsets.csv
      --layout-real-path layout.csv
      --n-trials 30
    deps:
      - src/run_optimize_layout.py
